// Extracted from assets/deobf.js animal id helpers and animalInfo() overrides.
const AnimalType = Object.freeze({
    1: 'Mouse',
    2: 'Rabbit',
    3: 'Pig',
    4: 'Fox',
    5: 'Deer',
    6: 'Mole',
    7: 'Zebra',
    8: 'Lion',
    9: 'CHEETAH',
    10: 'Bear',
    11: 'Croc',
    12: 'Rhino',
    13: 'Hippo',
    14: 'Dragon',
    15: 'Shrimp',
    16: 'Trout',
    17: 'Crab',
    18: 'Squid',
    19: 'Shark',
    20: 'Stingray',
    21: 'Turtle',
    22: 'Sea-horse',
    23: 'Jellyfish',
    24: 'The Kraken',
    25: 'Pufferfish',
    26: 'Killer Whale',
    27: 'Swordfish',
    28: 'Gorilla',
    29: 'Octopus',
    30: 'Wolf',
    31: 'Arctic Hare',
    32: 'The Yeti!',
    33: 'Chipmunk',
    34: 'Muskox',
    35: 'Penguin',
    36: 'Polar Bear',
    37: 'Seal',
    38: 'Snow leopard',
    39: 'Walrus',
    40: 'Reindeer',
    41: 'Arctic Fox',
    42: 'Wolverine',
    43: 'Mammoth',
    44: 'Donkey',
    45: 'Snail',
    46: 'Black Dragon',
    47: 'Sabertooth Tiger',
    48: 'Elephant',
    49: 'Blue Whale',
    50: 'Cobra',
    51: 'Boa Constrictor',
    52: 'Giant Spider',
    53: 'T-REX',
    54: 'Tiger',
    55: 'Giraffe',
    56: 'Eagle',
    57: 'Hedgehog',
    58: 'Duck',
    59: 'Duckling',
    60: 'Lemming',
    61: 'King Crab',
    62: 'Frog',
    63: 'Ostrich',
    64: 'Pelican',
    65: 'Falcon',
    66: 'Snowy Owl',
    67: 'Honey Bee',
    68: 'Phoenix',
    69: 'Baby Ostrich',
    70: 'Sea Monster',
    71: 'Land Monster',
    72: 'Ice Monster',
    73: 'Dino Monster',
    74: 'Pigeon',
    75: 'Toucan',
    76: 'Macaw',
    77: 'Flamingo',
    78: 'Cassowary',
    79: 'Chicken',
    80: 'Woodpecker',
    81: 'Peacock',
    82: 'Kangaroo Rat',
    83: 'Desert Chipmunk',
    84: 'Meerkat',
    85: 'Gazelle',
    86: 'Armadillo',
    87: 'Fennec Fox',
    88: 'Camel',
    89: 'Warthog',
    90: 'Hyena',
    91: 'Rattlesnake',
    92: 'Vulture',
    93: 'Bison',
    94: 'Komodo Dragon',
    95: 'Giant Scorpion',
    96: 'Pterodactyl',
    97: 'Gobi Bear',
    98: 'Blackwidow Spider',
    99: 'Bullet Ant',
    100: 'King Dragon',
    101: 'The Snowman',
    102: 'Santa!',
    103: 'Rudolph!',
    105: 'Markhor',
    106: 'The BigFoot',
    107: 'Jagga',
    108: 'Raven',
    109: 'Kakapo',
    110: 'Swinehoe',
    111: 'White Giraffe',
    112: 'Turkey!',
    113: 'Tarsier!',
    114: 'Chukar!',
    121: 'Flying Lizard!',
    122: 'Bird Monster',
});
